### ISSUE TITLE
Dever does not work when there are 2 projects with the same name but different locations

### ISSUE THREAD

**Issue by imaneAmc** [czprz/dever#85]
**To Reproduce**
1. Clone same project in different locations
2. execute dever init
3. execute dever projectname env --start

**Expected behavior**
choose which project to execute in which location

**Current Behaviour**
Components are not allowed to shared keywords

**Comment by czprz** [comment]
Currently known solutions:
* During 'dever init' allow users to choose which projects should included in .dever
* Support removing project from .dever after running 'dever init' through 'dever config'
* If keyword is found two places. User needs to choose which project they want to execute
* If keyword is found two places. Keywords are modified to be more unique for each project and can be found when using 'dever list'
